### ISSUE TITLE
节点重启过程中出现panic

### ISSUE THREAD

**Issue by ouohh** [AlayaNetwork/Alaya-Go#9]
环境：Alaya链
问题：Alaya节点进程重启出现panic，节点正常同步块高，这个是什么panic?
部分日志：
```
INFO [06-03|05:00:51.882|internal/debug/flags.go:191] Starting pprof server                    addr=http://127.0.0.1:6060/debug/pprof
DEBUG[06-03|05:00:51.882|platon/main.go:261]          Sanitizing Go's GC trigger               percent=100
INFO [06-03|05:00:53.637|cmd/utils/flags.go:904]      Maximum peer count                       ETH=20 LES=0 total=20
DEBUG[06-03|05:00:53.637|accounts/keystore/file_cache.go:87] FS scan times                            list=23.028µs set=523ns diff=1.219µs
DEBUG[06-03|05:00:53.637|accounts/keystore/file_cache.go:87] FS scan times                            list=12.458µs set=390ns diff=494ns
WARN [06-03|05:00:53.637|common/address.go:93]               the address prefix not set yet           input=atp1hzqghmjtzcggxa0clhaxddz0asdtkpmj23lv6j
WARN [06-03|05:00:53.637|common/address.go:93]               the address prefix not set yet           input=atp147txew2paj3y8kqthzelslxyyjmkzt0gwe99cr
WARN [06-03|05:00:53.637|common/address.go:93]               the address prefix not set yet           input=atp14cl7nrys9xlfcx6clpy4fs4rsasc2htdjz9unu
INFO [06-03|05:00:53.637|core/snapshotdb/snapshotdb.go:170]  set path                                 package=snapshotdb path=/opt/platon/data/platon/snapshotdb
INFO [06-03|05:00:53.638|node/node.go:181]                   Starting peer-to-peer node               instance=PlatONnetwork/platon-94.74.112.107/v0.15.0-unstable-9867ee68/linux-amd64/go1.13.4
INFO [06-03|05:00:53.638|ethdb/leveldb/leveldb.go:98]        Allocated cache and file handles         database=/opt/platon/data/platon/chaindata cache=805.31mB handles=524288
INFO [06-03|05:00:54.076|core/snapshotdb/snapshotdb.go:226]  open snapshot db Allocated cache and file handles package=snapshotdb cache=768      handles=524288 baseDB=true
DEBUG[06-03|05:00:54.110|eth/backend.go:142]                 read header number from chain db         height=0xc000a5e408
DEBUG[06-03|05:00:54.110|core/genesis.go:391]                genesisIssuance                          amount=105000000000000000000000000
INFO [06-03|05:00:54.111|x/gov/gov_params.go:42]             Init Govern parameters ...
WARN [06-03|05:00:54.111|core/state/statedb.go:500]          cannot find current active version, The ActiveVersion List is nil
INFO [06-03|05:00:54.111|core/genesis_data.go:262]           Write genesis version into genesis block genesis version=3330/0.13.2
WARN [06-03|05:00:54.111|core/state/statedb.go:500]          cannot find current active version, The ActiveVersion List is nil
INFO [06-03|05:00:54.111|core/genesis_data.go:273]           Set SetYearEndBalance                    genesisReward=2000000000000000000000000
panic: Failed Store staking: Failed to convert nodeID to address. nodeId:00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, error:id is invalid secp256k1 curve point

goroutine 1 [running]:
github.com/PlatONnetwork/PlatON-Go/core.(*Genesis).ToBlock(0xc000213cc0, 0x0, 0x0, 0x0, 0x0, 0x246dd8695ebe5947)
	/opt/jenkins/workspace/PlatON/build_ubuntu/core/genesis.go:427 +0x14c8
github.com/PlatONnetwork/PlatON-Go/core.SetupGenesisBlock(0x7fa86d6178b0, 0xc0000d2900, 0x7fa83853a750, 0xc0001ba1e0, 0xc000213cc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/jenkins/workspace/PlatON/build_ubuntu/core/genesis.go:182 +0x1b16
github.com/PlatONnetwork/PlatON-Go/eth.New(0xc00032d680, 0xc0000b5800, 0x30, 0x142a720, 0xc0004df7d0)
	/opt/jenkins/workspace/PlatON/build_ubuntu/eth/backend.go:200 +0x3e3
github.com/PlatONnetwork/PlatON-Go/cmd/utils.RegisterEthService.func2(0xc00032d680, 0xc0003d3680, 0xc0004df988, 0xc0001b1060, 0x2)
	/opt/jenkins/workspace/PlatON/build_ubuntu/cmd/utils/flags.go:1268 +0x46
github.com/PlatONnetwork/PlatON-Go/node.(*Node).Start(0xc000262400, 0x0, 0x0)
	/opt/jenkins/workspace/PlatON/build_ubuntu/node/node.go:200 +0x414
github.com/PlatONnetwork/PlatON-Go/cmd/utils.StartNode(0xc000262400)
	/opt/jenkins/workspace/PlatON/build_ubuntu/cmd/utils/cmd.go:67 +0x2f
main.startNode(0xc0001b4000, 0xc000262400)
	/opt/jenkins/workspace/PlatON/build_ubuntu/cmd/platon/main.go:308 +0x7e
main.platon(0xc0001b4000, 0xc0001b4000, 0xc0004dfb9f)
	/opt/jenkins/workspace/PlatON/build_ubuntu/cmd/platon/main.go:296 +0xe3
gopkg.in/urfave/cli%2ev1.HandleAction(0x12a65e0, 0x1508540, 0xc0001b4000, 0xc0000e02a0, 0x0)
	/home/jenkins/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0003be1a0, 0xc000032680, 0x19, 0x1a, 0x0, 0x0)
	/home/jenkins/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x58c
main.main()
	/opt/jenkins/workspace/PlatON/build_ubuntu/cmd/platon/main.go:282 +0x55
INFO [06-03|05:10:26.890|internal/debug/flags.go:191] Starting pprof server                    addr=http://127.0.0.1:6060/debug/pprof
DEBUG[06-03|05:10:26.891|platon/main.go:261]          Sanitizing Go's GC trigger               percent=100
CRIT [06-03|05:10:34.074|cmd/utils/flags.go:691]      Bootstrap URL invalid                    enode=enode://02dc695641f5cada2c685e3bf3dca0218a9dc7a5d5ce8165a2f5bee40d002d18ec6d899abaac1472d88b71e49691019766abd177b8d5d94f72f6f6dc842fded2@seed5.10a1.alaya.network:16789 err="invalid IP address"
INFO [06-03|05:20:26.176|internal/debug/flags.go:191] Starting pprof server                    addr=http://127.0.0.1:6060/debug/pprof
DEBUG[06-03|05:20:26.177|platon/main.go:261]          Sanitizing Go's GC trigger               percent=100
INFO [06-03|05:20:27.528|cmd/utils/flags.go:904]      Maximum peer count                       ETH=20 LES=0 total=20
DEBUG[06-03|05:20:27.528|accounts/keystore/file_cache.go:87] FS scan times                            list=26.553µs set=582ns diff=1.003µs
WARN [06-03|05:20:27.528|common/address.go:93]               the address prefix not set yet           input=atp1hzqghmjtzcggxa0clhaxddz0asdtkpmj23lv6j
WARN [06-03|05:20:27.528|common/address.go:93]               the address prefix not set yet           input=atp147txew2paj3y8kqthzelslxyyjmkzt0gwe99cr
WARN [06-03|05:20:27.528|common/address.go:93]               the address prefix not set yet           input=atp14cl7nrys9xlfcx6clpy4fs4rsasc2htdjz9unu
INFO [06-03|05:20:27.528|core/snapshotdb/snapshotdb.go:170]  set path                                 package=snapshotdb path=/opt/platon/data/platon/snapshotdb
INFO [06-03|05:20:27.528|node/node.go:181]                   Starting peer-to-peer node               instance=PlatONnetwork/platon-94.74.112.107/v0.15.0-unstable-9867ee68/linux-amd64/go1.13.4
INFO [06-03|05:20:27.529|ethdb/leveldb/leveldb.go:98]        Allocated cache and file handles         database=/opt/platon/data/platon/chaindata cache=805.31mB handles=524288
INFO [06-03|05:20:27.927|core/snapshotdb/snapshotdb.go:226]  open snapshot db Allocated cache and file handles package=snapshotdb cache=768      handles=524288 baseDB=true
DEBUG[06-03|05:20:27.945|eth/backend.go:142]                 read header number from chain db         height=0xc00096e308
DEBUG[06-03|05:20:27.945|core/genesis.go:391]                genesisIssuance                          amount=105000000000000000000000000
INFO [06-03|05:20:27.946|x/gov/gov_params.go:42]             Init Govern parameters ...
WARN [06-03|05:20:27.946|core/state/statedb.go:500]          cannot find current active version, The ActiveVersion List is nil
INFO [06-03|05:20:27.946|core/genesis_data.go:262]           Write genesis version into genesis block genesis version=3330/0.13.2
WARN [06-03|05:20:27.946|core/state/statedb.go:500]          cannot find current active version, The ActiveVersion List is nil
INFO [06-03|05:20:27.946|core/genesis_data.go:273]           Set SetYearEndBalance                    genesisReward=2000000000000000000000000
INFO [06-03|05:20:27.946|core/genesis_data.go:243]           Call genesisStakingData, Store genesis pposHash by stake data pposHash=0x7295d604de19dd08103512d60ae83aa09f6104c62ba2077dcc9a62b1a3d4319b
DEBUG[06-03|05:20:27.946|core/genesis.go:440]                ToBlock IntermediateRoot                 root=0xd642b328f17a365f8c45d93e201c53e5adc8ba6a1aa2fb52cf40412524adca1c
INFO [06-03|05:20:27.946|trie/database.go:921]               Persisted trie from memory database      nodes=12 size=2.12kB time=38.014µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=-246.00B
DEBUG[06-03|05:20:27.946|core/genesis.go:470]                Call ToBlock finished                    genesisHash=0xfb787fede6752e1a5ad85d2c6fc140454759be5e69d86d2425ceac22c23bd419
INFO [06-03|05:20:27.950|common/address.go:35]               addressPrefix  has set                   prefix=atp
INFO [06-03|05:20:27.950|core/snapshotdb/snapshotdb.go:864]  begin close snapshotdb                   package=snapshotdb path=/opt/platon/data/platon/snapshotdb
INFO [06-03|05:20:27.950|core/snapshotdb/snapshotdb.go:888]  snapshotdb closed                        package=snapshotdb


```

**Comment by benbaley** [comment]
can you take a look at this? @niuxiaojie81

**Comment by platonci** [comment]
this is a ci test.

**Comment by alayaci** [comment]
this is a ci test

**Comment by junjiequ123** [comment]
Panic after node reboot

-- add translation for search friendly

**Comment by benbaley** [comment]
fixed in #9
